# -*- coding: utf-8 -*-
"""Pembelajaran_mesin_tugas 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjK7n6wqk_bbccknD8OQNAQ0dO5XYkzK

Memuat Dataset dan menampilkannya
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df = pd.read_csv('melb_data.csv', sep=';')
df_numeric = df.select_dtypes(include=[np.number])

print(f"Bentuk data awal (baris, kolom): {df_numeric.shape}")
print(df.head())

"""Mengecek apakah ada missing value atau tidak, dan data mana saja yang ada dan jumlahnya ada berapa"""

print("Jumlah Missing Value SEBELUM ditangani:")
missing_before = df_numeric.isnull().sum()
print(missing_before[missing_before > 0].sort_values(ascending=False))

"""Membuat missing value menghilang menggunakan median dari masing" kolom"""

df_numeric = df_numeric.fillna(df_numeric.median())
print("\nJumlah Missing Value SESUDAH ditangani:")
missing_after = df_numeric.isnull().sum()
if missing_after.sum() == 0:
    print("Selamat! Semua missing value sudah berhasil dihilangkan (bernilai 0).")
else:
    print(missing_after[missing_after > 0])

"""Menampilkan outlier dari 4 kolom"""

kolom_sampel = ['Price', 'Landsize', 'Distance', 'Rooms']

plt.figure(figsize=(12, 8))
for i, col in enumerate(kolom_sampel, 1):
    plt.subplot(2, 2, i)
    sns.boxplot(x=df_numeric[col], color='lightcoral')
    plt.title(f'Outlier {col} (SEBELUM)')

plt.tight_layout()
plt.show()

"""Menangani Outlier dengan metode Interquartile Range (IQR)"""

def tangani_outlier(df_in, col_name):
    Q1 = df_in[col_name].quantile(0.25)
    Q3 = df_in[col_name].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_in[col_name] = np.where(df_in[col_name] > upper_bound, upper_bound, df_in[col_name])
    df_in[col_name] = np.where(df_in[col_name] < lower_bound, lower_bound, df_in[col_name])
    return df_in

for col in df_numeric.columns:
    df_numeric = tangani_outlier(df_numeric, col)

plt.figure(figsize=(12, 8))
for i, col in enumerate(kolom_sampel, 1):
    plt.subplot(2, 2, i)
    sns.boxplot(x=df_numeric[col], color='lightgreen')
    plt.title(f'Outlier {col} (SESUDAH)')

plt.tight_layout()
plt.show()

"""Melakukan PCA. Sebelum PCA, data wajib distandarisasi (StandardScaler) agar skalanya sama."""

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_numeric)

pca = PCA(n_components=0.90)
df_pca = pca.fit_transform(df_scaled)

print("--- HASIL REDUKSI DIMENSI PCA ---")
print(f"Bentuk data SEBELUM PCA : {df_scaled.shape} -> Memiliki {df_scaled.shape[1]} Kolom/Fitur")
print(f"Bentuk data SESUDAH PCA : {df_pca.shape} -> Berhasil diringkas menjadi {df_pca.shape[1]} Komponen Utama")